permalink: /:year:month:day/:title.html
url: http://icing.fun
baseurl: /

# variables
name: IcingTomato
description: Enjoy it while it lasts, because it never does.


# File management
include: [".htaccess"]
exclude: ["README.md"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Plugins
plugins:
  - coderay

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1