permalink: /:year:month:day/:title.html
url: http://icing.fun
baseurl: /

# variables
name: IcingTomato
description: Enjoy it while it lasts, because it never does.


# File management
include: [".htaccess"]
exclude: ["README.md"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

plugins:
  - rouge

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : false
    line_numbers: false
  rouge_options:
    line_numbers: false
highlighter: prism